server:
  port: 8899

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  # freemarker
  #  freemarker:
  #    suffix: .ftl
  #    # 关闭模板缓存，方便测试
  #    cache: false
  #    template-loader-path: classpath:/templates/

  thymeleaf:
    # 去除thymeleaf的html严格校验
    mode: HTML
    # 设定thymeleaf文件路径 默认为src/main/resources/templates
    prefix: classpath:/templates/
    # 建议在开发时关闭缓存,不然没法看到实时页面
    cache: false
    # 模板编码
    encoding: UTF-8
    servlet:
      content-type: text/html

  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml